### ISSUE TITLE
Ambiguous Mouse Pointer

### ISSUE THREAD

**Issue by Menn1s** [yennhio/yennhio.github.io#1]
Hi, I noticed that the mouse in the experience page (https://yennhio.github.io/experience/experience.html) makes it difficult for me to find the link and point at it with the mouse (it's not clear which part of the mouse is actually the pointer).

Thanks! Your site looks great btw. I would include a screenshot but my screenshotter isn't grabbing the mouse pointer.

**Comment by yennhio** [comment]
Hi @Menn1s, thank you for your kind feedback. The issue's been resolved. Give it a look!
